import angular from 'angular';
import moment from 'moment';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';
import 'angular-ui-router';
import 'angular-ui-bootstrap';
import 'angular-xeditable';
import _ from 'lodash';
window._ = _;
window.moment = moment;
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
//import './layout';
import './components';
//import './registration';
//import './home';
//import './profile';
//import './article';
import './services';
//import './auth';
//import './settings';
//import './editor';



// Create and bootstrap application
const requires = [
  'ui.router',
  'ui.bootstrap',
  'xeditable',
  'templates',
  //'app.layout',
  //'app.components',
  'app.components',
  //'app.home',
  //'app.profile',
  //'app.article',
  'app.services',
  //'app.auth',
  //'app.settings',
  //'app.editor'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});
