import angular from 'angular';
import moment from 'moment';
// Import our app config files
import constants from './config/app.constants';
import appConfig from './config/app.config';
import appRun from './config/app.run';
import 'angular-ui-router';
import 'angular-ui-bootstrap';
//import 'angular-xeditable';
import 'angular-ui-grid';
import 'ui-grid-auto-fit-columns';
import 'angular-google-chart';
import _ from 'lodash';
import 'angular-toastr';
window._ = _;
window.moment = moment;
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
//import './layout';
import './components';
//import './registration';
//import './home';
//import './profile';
//import './article';
import './services';
//import './auth';
//import './settings';
//import './editor';

// Create and bootstrap application
const requires = [
    'ui.router',
    'ui.bootstrap',
    'toastr',
    //'xeditable',
    'ui.grid',
    'ui.grid.edit',
    'ui.grid.exporter',
    'ui.grid.autoFitColumns',
    'ui.grid.pagination',
    'ui.grid.resizeColumns',
    'ui.grid.grouping',
    'googlechart',
    //'agGrid',
    'templates',
    //'app.layout',
    //'app.components',
    'app.components',
    //'app.home',
    //'app.profile',
    //'app.article',
    'app.services'
    //'app.auth',
    //'app.settings',
    //'app.editor'
];

//console.log(agGrid);

//agGrid.initialiseAgGridWithAngular1(angular);
// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
    strictDi: true
});